[build]
command = "git submodule update --init --recursive && hugo"
publish = "public"

[build.environment]
HUGO_VERSION = "0.146.0"

[context]
[context.branch-deploy]
command = "git submodule update --init --recursive && hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "git submodule update --init --recursive && hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"
